
MYSQL_ROOT_PASSWORD: "{{ (lookup('amazon.aws.aws_secret', 'prod/roboshop/mysql',region='us-east-1') |  from_json).MYSQL_ROOT_PASSWORD }}"

# "{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/mysql', region='us-east-1', decrypt=True) }}"
