$ANSIBLE_VAULT;1.1;AES256
33356239363264343765303239636234363463643631376438303765303537656338363936303033
3364333430303631643138353430376566616662366331380a356637396338613863633061623839
32343264373032366139313231316234376565386437326263316338363461313739313539636631
6235366631663761360a633835626464376164633966393438303765393938363161626531623630
36386261633634656663353835303336666665613838326239663961613663303830623964356631
6166333434393663363136643234643364333333393238646332