$ANSIBLE_VAULT;1.1;AES256
34356261656462313961333133386337323937346562333230363132356635313334623339306133
3836313436656438626233646661336533653230653130640a333163346161343333366332323463
61646535366233333532303462613865623036303765646364306433653031386538383638313065
6561663266613535660a626135343637346565336537633036613564323836336362646638623630
32393035633961313833346233653733313039353038393437386462663065386530643366303737
3465353531393865373266646466656538383934336539393736